create table "public"."organization_message_credits" (
    "id" bigint generated by default as identity not null,
    "organization_id" uuid not null,
    "credit_amount" bigint not null default '0'::bigint,
    "remaining_credits" bigint not null default '0'::bigint,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."organization_message_credits" enable row level security;

CREATE UNIQUE INDEX organization_message_credits_pkey ON public.organization_message_credits USING btree (id);

alter table "public"."organization_message_credits" add constraint "organization_message_credits_pkey" PRIMARY KEY using index "organization_message_credits_pkey";

alter table "public"."organization_message_credits" add constraint "organization_message_credits_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE not valid;

alter table "public"."organization_message_credits" validate constraint "organization_message_credits_organization_id_fkey";


