alter table "public"."organization_credits" drop constraint "organization_credits_organization_id_fkey";

alter table "public"."organization_credits" drop constraint "organization_credits_organization_id_key";

alter table "public"."organization_credits" drop constraint "organization_credits_pkey";

drop index if exists "public"."organization_credits_organization_id_key";

drop index if exists "public"."organization_credits_pkey";

drop table "public"."organization_credits";

create table "public"."organization_message_credits" (
    "id" bigint generated by default as identity not null,
    "organization_id" uuid not null,
    "credit_amount" bigint default '0'::bigint,
    "remaining_credits" bigint default '0'::bigint,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."organization_message_credits" enable row level security;

CREATE UNIQUE INDEX organization_credits_organization_id_key ON public.organization_message_credits USING btree (organization_id);

CREATE UNIQUE INDEX organization_credits_pkey ON public.organization_message_credits USING btree (id);

alter table "public"."organization_message_credits" add constraint "organization_credits_pkey" PRIMARY KEY using index "organization_credits_pkey";

alter table "public"."organization_message_credits" add constraint "organization_credits_organization_id_key" UNIQUE using index "organization_credits_organization_id_key";

alter table "public"."organization_message_credits" add constraint "organization_message_credits_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE not valid;

alter table "public"."organization_message_credits" validate constraint "organization_message_credits_organization_id_fkey";


CREATE OR REPLACE FUNCTION public.handle_new_organization()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Insert a new row into organization_message_credits table for the newly created organization
  INSERT INTO public.organization_message_credits (organization_id)
  VALUES (NEW.id);

  -- Insert a new row into api_keys table for the newly created organization
  INSERT INTO public.api_keys (organization_id)
  VALUES (NEW.id);

  RETURN NEW;
END;
$function$
;