create table "public"."waitlist" (
    "id" bigint generated by default as identity not null,
    "email" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."waitlist" enable row level security;

CREATE UNIQUE INDEX waitlist_pkey ON public.waitlist USING btree (id);

alter table "public"."waitlist" add constraint "waitlist_pkey" PRIMARY KEY using index "waitlist_pkey";

create policy "Enable insert access for all users"
on "public"."waitlist"
as permissive
for insert
to public
with check (true);



