name: Deploy intellisync migrations to staging

on:
  workflow_run:
    workflows: ['Monorepo tests']
    types: [completed]
  workflow_dispatch:


jobs:
  on-success:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_IS_DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.STAGING_IS_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: |
          cd apps/intellisync/server/
          supabase link --project-ref $STAGING_PROJECT_ID
          supabase db push

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
