name: Deploy intellisync migrations to staging

on:
  workflow_run:
    workflows: ["Monorepo tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_IS_DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.STAGING_IS_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: |
          cd apps/intellisync/server/
          supabase link --project-ref $STAGING_PROJECT_ID
          supabase db push